name: Support
description: Finding support on how to use the plugin
labels: ['support']
body:
    - type: textarea
      id: problem
      attributes:
          label: What do you need to help with?
      validations:
          required: true
